### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/@storefront-x%2frobots: Not found".

### ISSUE THREAD

**Issue by Watch3ruk** [storefront-x/storefront-x#130]
warning @storefront-x/core > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
error An unexpected error occurred: "https://registry.yarnpkg.com/@storefront-x%2frobots: Not found".

**Comment by adamjedlicka** [comment]
@Watch3ruk Thanks for the report. Fixed in v1.0.2.
